### ISSUE TITLE
System.TypeLoadException: DisposeAsync not implemented in bundled System.Text.Json 8.0 when using .NET 9.0

### ISSUE THREAD

**Issue by rdvanbuuren-gasunie** [reqnroll/Reqnroll#897]
### Reqnroll Version

3.1.2

### Which test runner are you using?

xUnit 2

### Test Runner Version Number

2.9.3

### .NET Implementation

.NET 9.0

### Test Execution Method

Command line – PLEASE SPECIFY THE FULL COMMAND LINE

It's during build of the solution in the pipeline.

``` yaml
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    projects: '$(Build.SourcesDirectory)/src/solution.sln'
    arguments: >
      /p:Version="$(Build.BuildNumber)"
      --configuration Release
      --no-incremental 
      --no-restore
      --nologo
      --verbosity detailed
```

### Content of reqnroll.json configuration file

```json
{
    "$schema": "https://schemas.reqnroll.net/reqnroll-config-latest.json",
    "generator": {
        "addNonParallelizableMarkerForTags": [
            "runIsolated"
        ]
    }
}
```

### Description
Reqnroll MSBuild generation fails on build agents with `System.TypeLoadException` when project targets .NET 9.0, due to version conflict between bundled System.Text.Json 8.0.0.0 and .NET 9.0's System.Text.Json 9.0.0.0.
 
### Error Message
```
[Reqnroll] System.TypeLoadException: Method 'DisposeAsync' in type 'System.Text.Json.Utf8JsonWriter' from assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' does not have an implementation.
   at Reqnroll.Configuration.JsonConfig.JsonConfigurationSourceGenerator.Create_JsonConfig(JsonSerializerOptions options)
```
 
### Environment
- **Reqnroll version**: 3.1.2
- **Target framework**: net9.0
- **.NET SDK version**: 9.0.102
- **MSBuild context**: Azure DevOps build agents (Linux)
- **Package management**: Central Package Management with Directory.Packages.props
 
### Root Cause Analysis
The issue stems from assembly loading conflicts in MSBuild context:
 
1. **Reqnroll.Tools.MsBuild.Generation 3.1.2** bundles System.Text.Json 8.0.0.0
2. **.NET 9.0 projects** expect System.Text.Json 9.0.0.0 with newer APIs
3. **MSBuild plugin context** loads the older version first, causing TypeLoadException when trying to use .NET 9 APIs
 
Build agent logs show:
```
[Reqnroll]   System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51;/home/AzDevOps/.nuget/packages/microsoft.azure.functions.worker.sdk/2.0.5/tools/netstandard2.0/System.Text.Json.dll (TaskId:4290)
[Reqnroll]   System.Text.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51;/opt/hostedtoolcache/dotnet/shared/Microsoft.NETCore.App/9.0.10/System.Text.Json.dll (TaskId:4290)

Assembly loaded during TaskRun (Reqnroll.Tools.MsBuild.Generation.GenerateFeatureFileCodeBehindTask): System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51 (location: /home/AzDevOps/.nuget/packages/reqnroll.tools.msbuild.generation/3.1.2/build/netstandard2.0/System.Text.Json.dll, MVID: 0dce814b-52c5-44dd-b543-5914204265e7, AssemblyLoadContext: MSBuild plugin /home/AzDevOps/.nuget/packages/reqnroll.tools.msbuild.generation/3.1.2/build/netstandard2.0/Reqnroll.Tools.MsBuild.Generation.dll) (TaskId:4290)

##[error]/home/AzDevOps/.nuget/packages/reqnroll.tools.msbuild.generation/3.1.2/build/Reqnroll.Tools.MsBuild.Generation.targets(93,5): Error : [Reqnroll] System.TypeLoadException: Method 'DisposeAsync' in type 'System.Text.Json.Utf8JsonWriter' from assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' does not have an implementation.
   at Reqnroll.Configuration.JsonConfig.JsonConfigurationSourceGenerator.Create_JsonConfig(JsonSerializerOptions options)
   at Reqnroll.Configuration.JsonConfig.JsonConfigurationSourceGenerator.global::System.Text.Json.Serialization.Metadata.IJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type)
   at System.Text.Json.JsonSerializerOptions.CachingContext.CreateCacheEntry(Type type, CachingContext context)
```
 
### Possible Solutions
1. **Update bundled dependencies**: Update Reqnroll.Tools.MsBuild.Generation to use System.Text.Json 9.0+ compatible version
2. **Remove bundled assemblies**: Let MSBuild resolve System.Text.Json from the project's dependencies instead of bundling
3. **Assembly binding configuration**: Provide guidance for assembly binding redirects in MSBuild context
 
### Additional Context
- Issue only occurs on build agents, not local development (due to different assembly resolution behavior)
 
### Workarounds Attempted
- `CopyLocalLockFileAssemblies=true`
- Assembly binding redirects
- Conditional package versioning for build agents

### Steps to Reproduce

1. Create a .NET 9.0 project with Reqnroll.xUnit 3.1.2
2. Use Central Package Management with System.Text.Json 9.0.10
3. Build on a clean environment (Azure DevOps build agent)
4. Observe MSBuild generation failure

**Comment by gasparnagy** [comment]
> [@gasparnagy](https://github.com/gasparnagy) I can confirm this issue doesn't occur with v3.0.3

That's a good news. Then we need to just check what dependencies we bundled with v3.0.3 and how that changed with #812 and adapt. 

//CC @Code-Grump

**Comment by Code-Grump** [comment]
A key thing to understand is that the generator's dependencies are separate from the project's. The generator is loaded into the MSBuild runtime, so it's dependencies are resolved from that runtime.

**Comment by Code-Grump** [comment]
Having compared the two packages, I can't see any meaningful difference. I suspect we're a victim of DLL load ordering and that our `netstandard2.0` package incorporates .NET 8 libraries and will always bump into problems running against other non-Framework runtimes.

**Comment by janssen-io** [comment]
If the script task below installs the CI-version (`3.2.2-ci...`) correctly (after adding them to source control), then unfortunately that version does not resolve the issue. That is, the build step still shows the same TypeLoadException.

> /home/vsts/.nuget/packages/reqnroll.tools.msbuild.generation/**3.2.2-ci20251118-2041**/build/Reqnroll.Tools.MsBuild.Generation.targets(93,5): error : [Reqnroll] System.TypeLoadException: Method 'DisposeAsync' in type 'System.Text.Json.Utf8JsonWriter' from assembly 'System.Text.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' does not have an implementation.

Script task ran in the directory of the test project that uses Reqnroll.
```bash
source_path="$(pwd)/localNuget"
mkdir $source_path
dotnet nuget add source $source_path -n localNuget
dotnet nuget push ./*.nupkg -s localNuget

dotnet restore

declare -a packages=(
    "Reqnroll"
    "Reqnroll.xunit.v3"
    "Reqnroll.Microsoft.Extensions.DependencyInjection"
  )
for pkg in "${packages[@]}"
do
    dotnet add package $pkg -v 3.2.2-ci20251118-2041 -s localNuget
done
```

**Comment by FrancisGauthier** [comment]
I confirm that version 3.3.0 has fixed the issue in my pipelines!

using azure devops

Pool: [Azure Pipelines]
Image: ubuntu-latest
